import { MapType } from "./types";

export const testData: MapType = {
  container: {
    type: 'room',
    width: 1600,
    height: 800,
  },
  components: [
    {
      type: 'STORE',
      x: 20,
      y: 20,
      width: 60,
      height: 100,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '1_2', name: 'A01' },
    },
    {
      type: 'NET',
      x: 120,
      y: 20,
      width: 60,
      height: 100,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '2_2', name: 'A02' },
    },
    {
      type: 'CAB',
      x: 220,
      y: 20,
      width: 60,
      height: 100,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '3_2', name: 'A03' },
    },
    {
      type: 'WIRING',
      x: 320,
      y: 20,
      width: 60,
      height: 100,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '4_2', name: 'A04' },
    },
    {
      type: 'IT',
      x: 420,
      y: 20,
      width: 60,
      height: 100,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '5_2', name: 'A05' },
    },
    {
      type: 'UPS',
      x: 520,
      y: 20,
      width: 60,
      height: 100,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '6_2', name: 'A06' },
    },
    {
      type: 'BAT',
      x: 620,
      y: 20,
      width: 60,
      height: 100,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '7_2', name: 'A07' },
    },
    {
      type: 'BATRACK',
      x: 720,
      y: 20,
      width: 80,
      height: 51,
      zIndex: 10,
      config: { direction: 'up', column: 2, row: 3 },
      asset: { id: '8_2', name: 'A08' },
    },
    {
      type: 'FIREHOST',
      x: 820,
      y: 20,
      width: 60,
      height: 100,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '9_2', name: 'A09' },
    },
    {
      type: 'FIREBOTTLE',
      x: 920,
      y: 20,
      width: 40,
      height: 40,
      zIndex: 10,
      config: {},
      asset: { id: '10_2', name: 'A10' },
    },
    {
      type: 'AC',
      x: 1020,
      y: 20,
      width: 180,
      height: 85,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '11_2', name: 'A11' },
    },
    {
      type: 'FRESHAIR',
      x: 1020,
      y: 120,
      width: 180,
      height: 85,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '12_2', name: 'A12' },
    },
    {
      type: 'SD',
      x: 1270,
      y: 20,
      width: 30,
      height: 30,
      zIndex: 10,
      config: {},
      asset: { id: '13_2', name: 'A13' },
    },
    {
      type: 'TAHS',
      x: 1370,
      y: 20,
      width: 30,
      height: 30,
      zIndex: 10,
      config: {},
      asset: { id: '14_2', name: 'A14' },
    },
    {
      type: 'CAMERA',
      x: 1470,
      y: 20,
      width: 30,
      height: 30,
      zIndex: 10,
      config: {},
      asset: { id: '15_2', name: 'A15' },
    },
  ],
};

export const testData2: MapType = {
  container: {
    type: 'room',
    width: 1600,
    height: 800,
  },
  components: [
    {
      type: 'STORE',
      x: 20,
      y: 20,
      width: 60,
      height: 100,
      zIndex: 10,
      config: { direction: 'up' },
      asset: { id: '22_2', name: 'A222' },
    },
  ],
};
